/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AssetsAtRiskRouteImport } from './routes/assets-at-risk'
import { Route as FutureAiEnhancementsRouteImport } from './routes/future-ai-enhancements'
import { Route as MapRouteImport } from './routes/map'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsAtRiskRoute = AssetsAtRiskRouteImport.update({
  id: '/assets-at-risk',
  path: '/assets-at-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureAiEnhancementsRoute = FutureAiEnhancementsRouteImport.update({
  id: '/future-ai-enhancements',
  path: '/future-ai-enhancements',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets-at-risk': typeof AssetsAtRiskRoute
  '/future-ai-enhancements': typeof FutureAiEnhancementsRoute
  '/map': typeof MapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets-at-risk': typeof AssetsAtRiskRoute
  '/future-ai-enhancements': typeof FutureAiEnhancementsRoute
  '/map': typeof MapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assets-at-risk': typeof AssetsAtRiskRoute
  '/future-ai-enhancements': typeof FutureAiEnhancementsRoute
  '/map': typeof MapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/assets-at-risk' | '/future-ai-enhancements' | '/map'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/assets-at-risk' | '/future-ai-enhancements' | '/map'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assets-at-risk'
    | '/future-ai-enhancements'
    | '/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssetsAtRiskRoute: typeof AssetsAtRiskRoute
  FutureAiEnhancementsRoute: typeof FutureAiEnhancementsRoute
  MapRoute: typeof MapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets-at-risk': {
      id: '/assets-at-risk'
      path: '/assets-at-risk'
      fullPath: '/assets-at-risk'
      preLoaderRoute: typeof AssetsAtRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-ai-enhancements': {
      id: '/future-ai-enhancements'
      path: '/future-ai-enhancements'
      fullPath: '/future-ai-enhancements'
      preLoaderRoute: typeof FutureAiEnhancementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssetsAtRiskRoute: AssetsAtRiskRoute,
  FutureAiEnhancementsRoute: FutureAiEnhancementsRoute,
  MapRoute: MapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
